[tox]
envlist =
    py{310,311,312,313}-dj52-wt70
    py{310,311,312,313,314}-dj52-wt{73,74}
    py{312,313,314}-dj60-wt{73,74}
    lint

[flake8]
# E203: Whitespace before ':'. Black should take care of this.
# E501: Ignore line length rules. Black should take care of this.
# W503: Ignore line break before binary operator which is due to change anyway (https://www.flake8rules.com/rules/W503.html)
ignore=E203,E501,W503

exclude=.git,__pycache__,dist,.tox,venv,*/migrations/*

[pytest]
DJANGO_SETTINGS_MODULE = testapp.settings.dev
pythonpath = testapp

[testenv:lint]
extras = linting
commands = flake8 .

[testenv]
install_command = pip install {opts} {packages}
extras = testing
deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    wt70: wagtail>=7.0,<7.1
    wt73: wagtail>=7.3,<7.4
    wt74: wagtail>=7.4,<7.5
commands =
    python testapp/manage.py makemigrations
    python testapp/manage.py migrate
    python testapp/manage.py loaddata testapp/testdata_wt3.json # Make sure the testapp data is installable
    pytest .

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
